### ISSUE TITLE
Support for Limesurvey 3.xx

### ISSUE THREAD

**Issue by SBriere** [SondagesPro/LS-sendPdfReport#1]
We are planning an upgrade from Limesurvey 2.xx to Limesurvey 3.xx.

Our current installation setup has that plugin installed and working perfectly. However, it would seem that the plugin system has changed in 3.xx. Any plan to update the plugin to 3.xx?

Currently, an error is generated in the 3.xx version: "Fatal error: Class 'ls\pluginmanager\PluginBase' not found in plugins/sendPdfReport/sendPdfReport.php on line 23"

Thank you!

**Comment by Shnoulle** [comment]
I don't update sendPdfReport for 3.0. This plugin was replaced by [pdfReport](https://gitlab.com/SondagesPro/ExportAndStats/pdfReport)

With pdfReport you have same system than send PdfReport but for question directly (in advanced settings), with more option. And pdfReport work in 2.7X. 

I have the projet to fix pdfReport for 3.0 , there are less update to do. I make a quick fix and you can test.
